# ============================================================
# ธีมสี IEAT Modern
# ============================================================

COLOR_PRIMARY = "#3E215D"
COLOR_SECONDARY = "#284E78"
COLOR_GREEN = "#5D8233"
COLOR_ACCENT = "#ECD662"

COLOR_WHITE = "#FFFFFF"
COLOR_BACKGROUND = "#F7F8FA"
COLOR_SURFACE = "#FFFFFF"
COLOR_TEXT = "#22252A"
COLOR_MUTED = "#6B7280"
COLOR_BORDER = "#E3E6EA"

COLOR_RED = "#D64545"
COLOR_RED_BACKGROUND = "#FFF3F3"

COLOR_GREEN_BACKGROUND = "#F3F7EE"
COLOR_BLUE_BACKGROUND = "#F2F6FA"
COLOR_PURPLE_BACKGROUND = "#F6F2F8"
COLOR_YELLOW_BACKGROUND = "#FFFBEA"

# รองรับชื่อเดิมในโค้ด ไม่ต้องแก้ทุกจุด
COLOR_TEAL = COLOR_GREEN
COLOR_LIGHT_TEAL = COLOR_ACCENT
